/**
 * Actions tracked by the audit system.
 */
export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  VERIFY = 'VERIFY',
  REJECT = 'REJECT',
  PROCESS = 'PROCESS',

  // Authorization & user management actions
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',
  USER_ASSIGNED_TO_PROJECT = 'USER_ASSIGNED_TO_PROJECT',
  USER_REMOVED_FROM_PROJECT = 'USER_REMOVED_FROM_PROJECT',
  USER_ACTIVATED = 'USER_ACTIVATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',

  // Application lifecycle actions (Phase 2)
  APPLICATION_CREATED = 'APPLICATION_CREATED',
  APPLICATION_UPDATED = 'APPLICATION_UPDATED',
  APPLICATION_SUBMITTED = 'APPLICATION_SUBMITTED',
  APPLICATION_REVIEW_STARTED = 'APPLICATION_REVIEW_STARTED',
  APPLICATION_INFORMATION_REQUESTED = 'APPLICATION_INFORMATION_REQUESTED',
  APPLICATION_APPROVED = 'APPLICATION_APPROVED',
  APPLICATION_REJECTED = 'APPLICATION_REJECTED',
  APPLICATION_CANCELLED = 'APPLICATION_CANCELLED',
  APPLICATION_COMMENT_ADDED = 'APPLICATION_COMMENT_ADDED',

  // Project lifecycle actions (Phase 2)
  PROJECT_INITIALIZED_FROM_APPLICATION = 'PROJECT_INITIALIZED_FROM_APPLICATION',
  PROJECT_ACTIVATED = 'PROJECT_ACTIVATED',
}
