/**
 * Actions tracked by the audit system.
 */
export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  VERIFY = 'VERIFY',
  REJECT = 'REJECT',
  PROCESS = 'PROCESS',

  // Authorization & user management actions
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',
  USER_ASSIGNED_TO_PROJECT = 'USER_ASSIGNED_TO_PROJECT',
  USER_REMOVED_FROM_PROJECT = 'USER_REMOVED_FROM_PROJECT',
  USER_ACTIVATED = 'USER_ACTIVATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
}
