/**
 * Centralized error code constants.
 * Used in AppError and error responses for machine-readable error identification.
 */
export const ErrorCodes = {
  // Client errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',

  // Server errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Domain-specific
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  PROCESSING_FAILED: 'PROCESSING_FAILED',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',

  // Authorization
  INSUFFICIENT_PERMISSION: 'INSUFFICIENT_PERMISSION',
  PROJECT_ACCESS_DENIED: 'PROJECT_ACCESS_DENIED',
  DUPLICATE_ASSIGNMENT: 'DUPLICATE_ASSIGNMENT',
  SELF_ROLE_CHANGE: 'SELF_ROLE_CHANGE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
