/**
 * Granular permissions in the STRATA platform.
 *
 * Each permission represents a specific action on a specific resource type.
 * Permissions are mapped to roles in role-permissions.ts — not hardcoded in controllers.
 */
export enum Permission {
  // User management
  USER_READ = 'USER_READ',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_MANAGE = 'USER_MANAGE',

  // Projects
  PROJECT_CREATE = 'PROJECT_CREATE',
  PROJECT_READ = 'PROJECT_READ',
  PROJECT_UPDATE = 'PROJECT_UPDATE',
  PROJECT_DELETE = 'PROJECT_DELETE',
  PROJECT_ASSIGN = 'PROJECT_ASSIGN',

  // Parcels
  PARCEL_CREATE = 'PARCEL_CREATE',
  PARCEL_READ = 'PARCEL_READ',
  PARCEL_UPDATE = 'PARCEL_UPDATE',
  PARCEL_DELETE = 'PARCEL_DELETE',

  // Buildings
  BUILDING_CREATE = 'BUILDING_CREATE',
  BUILDING_READ = 'BUILDING_READ',
  BUILDING_UPDATE = 'BUILDING_UPDATE',
  BUILDING_DELETE = 'BUILDING_DELETE',

  // Floors
  FLOOR_CREATE = 'FLOOR_CREATE',
  FLOOR_READ = 'FLOOR_READ',
  FLOOR_UPDATE = 'FLOOR_UPDATE',
  FLOOR_DELETE = 'FLOOR_DELETE',

  // Spatial assets
  SPATIAL_ASSET_CREATE = 'SPATIAL_ASSET_CREATE',
  SPATIAL_ASSET_READ = 'SPATIAL_ASSET_READ',
  SPATIAL_ASSET_UPDATE = 'SPATIAL_ASSET_UPDATE',
  SPATIAL_ASSET_DELETE = 'SPATIAL_ASSET_DELETE',

  // Geometry
  GEOMETRY_CREATE = 'GEOMETRY_CREATE',
  GEOMETRY_READ = 'GEOMETRY_READ',
  GEOMETRY_UPDATE = 'GEOMETRY_UPDATE',
  GEOMETRY_DELETE = 'GEOMETRY_DELETE',

  // Processing
  PROCESSING_CREATE = 'PROCESSING_CREATE',
  PROCESSING_READ = 'PROCESSING_READ',

  // Review
  REVIEW_READ = 'REVIEW_READ',
  REVIEW_APPROVE = 'REVIEW_APPROVE',
  REVIEW_REJECT = 'REVIEW_REJECT',

  // Registration
  REGISTRATION_READ = 'REGISTRATION_READ',
  REGISTRATION_APPROVE = 'REGISTRATION_APPROVE',
  REGISTRATION_REJECT = 'REGISTRATION_REJECT',

  // Audit
  AUDIT_READ = 'AUDIT_READ',

  // Applications (Phase 2)
  APPLICATION_CREATE = 'APPLICATION_CREATE',
  APPLICATION_READ = 'APPLICATION_READ',
  APPLICATION_READ_ALL = 'APPLICATION_READ_ALL',
  APPLICATION_UPDATE = 'APPLICATION_UPDATE',
  APPLICATION_SUBMIT = 'APPLICATION_SUBMIT',
  APPLICATION_START_REVIEW = 'APPLICATION_START_REVIEW',
  APPLICATION_REQUEST_INFORMATION = 'APPLICATION_REQUEST_INFORMATION',
  APPLICATION_APPROVE = 'APPLICATION_APPROVE',
  APPLICATION_REJECT = 'APPLICATION_REJECT',
  APPLICATION_CANCEL = 'APPLICATION_CANCEL',
  APPLICATION_COMMENT = 'APPLICATION_COMMENT',
  APPLICATION_INITIALIZE_PROJECT = 'APPLICATION_INITIALIZE_PROJECT',

  // Project Activation (Phase 2)
  PROJECT_ACTIVATE = 'PROJECT_ACTIVATE',
}
